server:
  port: 8084
app:
  values:
    api:
      giga-chat:
        base-url:
          auth: "https://ngw.devices.sberbank.ru:9443"
          chat: "https://gigachat.devices.sberbank.ru"
        chat-settings:
          scope: "GIGACHAT_API_PERS"
        auth-key: "OGYwZTY3YTctMjllNi00NGM5LTg3ZGYtZmFkZTljODE5YjYwOjE1MzFhZGFjLTRkYzUtNGYwYS05ZDI1LTZiOWUwMzlkYzYzNw=="

spring:
  datasource:
    url: jdbc:postgresql://91.146.28.240:5222/topic
    username: topic
    password: topic
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # ???????????: ????????? ???? ??????????
  jpa:
    hibernate:
      ddl-auto: update  # ????? ????????????: create, create-drop, validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #  sql:
  #    init:
  #      mode: always
  #      schema-locations: classpath:schema.sql
  application:
    name: ideathesis-topic-service
